---
# tasks file for pivoting
- name: "Install sshuttle"
  apt: 
    name: sshuttle
    state: present
  become: true
  become_method: sudo
- name: "Install chisel"
  apt: 
    name: chisel
    state: present
  become: true
  become_method: sudo
