---
# tasks file for pivoting
- name: "Install sshuttle"
  apt: 
    name: sshuttle
    state: present
  become: true
  become_method: sudo
- name: Install Dnscat2
  apt: 
    name: 
      - dnscat2
      - dnscat2-client
      - dnscat2-server
    state: present
  become: true
  become_method: sudo
