---
- name: "Install Tmux"
  apt: 
    name: tmux
    state: present
  become: true
  become_method: sudo
- name: "Copy Tmux Config"
  copy:
    src: "{{ role_path }}/files/tmux.conf"
    dest: "{{ ansible_env.HOME }}/.tmux.conf"
- name: "Install Tmux Plugin Manager (TPM)"
  ansible.builtin.shell: "ls ~/.tmux/plugins/tpm || git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm"
