---
- name: "Install Tmux"
  apt: 
    name: tmux
    state: present
  become: true
  become_method: sudo
- name: "Copy Tmux Config"
  copy:
    src: "{{ role_path }}/files/tmux.conf"
    dest: "{{ ansible_env.HOME }}/.tmux.conf"
- name: "Install Tmux Plugin Manager (TPM)"
  ansible.builtin.git:
    repo: https://github.com/tmux-plugins/tpm
    dest: ~/.tmux/plugins/tpm
    single_branch: yes
    version: master
