---
- name: "Install pipx"
  apt: 
    name: pipx
    state: present
  become: true
  become_method: sudo
- name: "Update PATH"
  command: pipx ensurepath
- name: "Install netexec"
  community.general.pipx:
    name: tox
    source: git+https://github.com/Pennyw0rth/NetExec
