---
- name: "Install xxd (hex encoder/decoder)"
  apt: 
    name: xxd
    state: present
  become: true
  become_method: sudo
- name: "Install Nishang"
  apt: 
    name: nishang
    state: present
  become: true
  become_method: sudo
