---
- name: "Install creds"
  ansible.builtin.pip:
    name: defaultcreds-cheat-sheet
- name: "Install seclists"
  apt: 
    name: seclists
    state: present
  become: true
  become_method: sudo
- name: "Install CUPP"
  apt: 
    name: cupp
    state: present
  become: true
  become_method: sudo
