---
- name: "Install creds"
  ansible.builtin.pip:
    name: defaultcreds-cheat-sheet
- name: "Install seclists"
  apt: 
    name: seclists
    state: present
  become: true
  become_method: sudo
- name: "Install CUPP"
  apt: 
    name: cupp
    state: present
  become: true
  become_method: sudo
- name: "Install Username Anarchy"
  ansible.builtin.git:
    repo: https://github.com/urbanadventurer/username-anarchy.git
    dest: /usr/share/username-anarchy
    single_branch: yes
    force: true
    version: master
  become: true
  become_method: sudo
