---
- name: "Install GVM for OpenVAS"
  apt: 
    name: gvm
    state: present
  become: true
  become_method: sudo
- name: "Install feroxbuster"
  apt: 
    name: feroxbuster
    state: present
  become: true
  become_method: sudo
