# Helpful links:
# https://docs.ansible.com/ansible/latest/reference_appendices/special_variables.html
---
- name: "Customize PenBox"
  hosts: localhost
  connection: local
  tasks:
    #- name: "Demo Debug"
    #  debug:
    #    msg: "{{ ansible_env.HOME }}"
    - name: Tmux Next Steps
      ansible.builtin.debug:
        msg: For first time install, finish installing tmux logging plugin. Enter tmux and execute [Prefix + I].
  roles:
    - role: "dependencies"
    - role: "configure-profile"
    - role: "configure-tmux"
    - role: "customize-vim"
    - role: "coding"
    - role: "pivoting"
    - role: "netexec"
    - role: "zap"
    - role: "password-tools"
    - role: "scan-tools"
    - role: "file-transfer-tools"
    - role: "exploit-tools"
    - role: "useful-tools"
    - role: "web-tools"
